# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MCyvi9iU10jHcXeOUA2JO8khRZtKlrmi9VWM9OISvw3F5p5+JXNuseeb3JcOWpCsHksoWymvrFLZwG8nVdCx0c6LDg5srtWGBBbJI/JABVw2YXhaqCaSqWkh3ClCobZpXbJggLBoNmFznpajetrgidnWnOuBG8eDxP6e2w7yPjxWqFlIZQXy/FKqjkzPUMazwsxBnrgTEASaiHkXYFa0aBnt9siJIXmXD0F4ef+J1BSbA6vCwlVETcxmtL3RxBwbZBtsAi6+MuCzz5/3X/TDxi4ADOlguvoASnYnfjJNk8ZrfcvgyE4+7bNaRSQph/dNEzeWd9eSA2p5KqksQ6KyrMlpsTZKdlwGXJijJawysRnd3T5sTQhXbtTb+Vx1X+kazuZ/+FcBIzSn6CshPuFIwSldB8iT/hWEuC8oC2G9we2pqCrIdhtKciTF1PDVydPnzGPpENE1TIpL6lDOt/7x1yZWrcJA6W/KMAlIqqSoGWW2hrAuiMsp37Px5zLm6UsrK8R7stcplxbSFuZPIT+c4BXKZ/5gRaMwzswA7AZuMXDTJWSNankcGLX+S4lM6dqy4QmWonNiVan2yKDtfu+A5Nzc1KEKnCo6GR9WmDkJCns6XZa88actgKy9JHp2zCo8mISdWcSIWlVXj9OoqxNGZ/y93ilqXpKyLp6Z+D8qeeM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
