travis:
  secure:
    BINSTAR_TOKEN: ad1/IxHVGpE1CyN7o/laNUxVvjPLs2Yvh+ertfuS7nXOxneGmU9AxJFN/ZqS8prZFwAzyuGIXmLXTFn7e91i5kTruDyIskT8GqNR7pu1Ds9M3jw4JgxhllPRchuoDIu/QctNujEUpncW+EavkQGnjkQroovI+sQjzhB5t1W2TgRyy7nvVdVcSnBfk236a4F4+qMmBGeHIR5vYd57pEpsZE2BfO3GeN3q09HxmqbULQLAz1Cnzs5zdLT8o8HLidC8h5cakoLnU4hQ+NPb5yNizBratXg55W8tQgapC240pJ90WHiKEModffM2489c3ULBC790sL+VOG0uMmA7IYjh/Uqej3SrSfNZNkeAyalyZjYaODQvD61pKVi8qhfvWO7ZZT0F+XMyIVmi3gWTQAbj/Jvyg1soyiaP7BW1ezCytkOwNO4f8Nak5wrwIMqF2NddF4RNvyGfnZV5AmNhes/F90oTiEi4OZt6rQ8dxnHzuviTU5K7k7Xff4T1puqnW/OvTuLRYL8J7MXJpdDbrcEg47mrlELIOimMeCnYNf+vpABmS4nZdLY51fn1hsxtAgAhjSDnnnEWBco5+SHye8/k3IXk/yZWJtFz7EuR4HiP3iWRUskkRtKCYYhLCXed24FA19kbyvxBabVvKdpMvN4Ks1vUK/oPF5UvZfQ4A17nPcU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
