travis:
  secure:
    BINSTAR_TOKEN: MCyvi9iU10jHcXeOUA2JO8khRZtKlrmi9VWM9OISvw3F5p5+JXNuseeb3JcOWpCsHksoWymvrFLZwG8nVdCx0c6LDg5srtWGBBbJI/JABVw2YXhaqCaSqWkh3ClCobZpXbJggLBoNmFznpajetrgidnWnOuBG8eDxP6e2w7yPjxWqFlIZQXy/FKqjkzPUMazwsxBnrgTEASaiHkXYFa0aBnt9siJIXmXD0F4ef+J1BSbA6vCwlVETcxmtL3RxBwbZBtsAi6+MuCzz5/3X/TDxi4ADOlguvoASnYnfjJNk8ZrfcvgyE4+7bNaRSQph/dNEzeWd9eSA2p5KqksQ6KyrMlpsTZKdlwGXJijJawysRnd3T5sTQhXbtTb+Vx1X+kazuZ/+FcBIzSn6CshPuFIwSldB8iT/hWEuC8oC2G9we2pqCrIdhtKciTF1PDVydPnzGPpENE1TIpL6lDOt/7x1yZWrcJA6W/KMAlIqqSoGWW2hrAuiMsp37Px5zLm6UsrK8R7stcplxbSFuZPIT+c4BXKZ/5gRaMwzswA7AZuMXDTJWSNankcGLX+S4lM6dqy4QmWonNiVan2yKDtfu+A5Nzc1KEKnCo6GR9WmDkJCns6XZa88actgKy9JHp2zCo8mISdWcSIWlVXj9OoqxNGZ/y93ilqXpKyLp6Z+D8qeeM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
